version: '3.5'
services:
  api1: # API - Instância 01
    image: thelinuxlich/gleba:latest
    hostname: api1
    depends_on:
      - db
    expose:
      - "80"
    links:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.25GB'

  api2: # API - Instância 01
    image: thelinuxlich/gleba:latest
    hostname: api2
    depends_on:
      - db
    expose:
      - "80"
    links:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.25GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    tmpfs:
      - /tmp/people-cache:rw,nodev,nosuid,size=500M
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'

  db: # Banco de dados
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: test
     POSTGRES_USER: postgres
     POSTGRES_DB: postgres
   expose:
    - "5432"
   ports:
    - 9998:5432
   volumes:
    - ./bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
    - ./postgresql.conf:/etc/postgresql/postgresql.conf
   command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
   deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.5GB'