version: '3.5'
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '2.1GB'
  
  api01:
    image: zanfranceschi/rinha-api-2023
    hostname: rinha-api01
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;Connection Pruning Interval=1;Connection Idle Lifetime=2;Enlist=false;No Reset On Close=true
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.4GB'
  
  api02:
    image: zanfranceschi/rinha-api-2023
    hostname: rinha-api02
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;Connection Pruning Interval=1;Connection Idle Lifetime=2;Enlist=false;No Reset On Close=true
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.4GB'
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.1GB'

networks:
  default:
    driver: bridge
    name: rinha