version: '3.5'
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '1GB'

  cache:
    hostname: cache
    image: redislabs/redisearch:latest
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.7GB'
  
  api01:
    image: zanfranceschi/rinha-api-2023
    hostname: rinha-api01
    depends_on:
      - db
      - cache
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;Connection Pruning Interval=1;Connection Idle Lifetime=2;Enlist=false;No Reset On Close=true
      - CACHE_CONNECTION_STRING=cache
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'
  
  api02:
    image: zanfranceschi/rinha-api-2023
    hostname: rinha-api02
    depends_on:
      - db
      - cache
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;Connection Pruning Interval=1;Connection Idle Lifetime=2;Enlist=false;No Reset On Close=true
      - CACHE_CONNECTION_STRING=cache
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'

networks:
  default:
    driver: bridge
    name: rinha